"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";

type Section = { id: string; name: string; skill: string; timeLimitSec: number; passages: Array<{ id: string; title: string }>; questions: Array<{ id: string; prompt: string; type: { code: string } }> };
type Exam = { id: string; code: string; name: string; sections: Section[]; testForms: Array<{ id: string; name: string; version: number; isPublished: boolean; sections: Array<{ sectionId: string; order: number }>; _count: { sessions: number } }> };
type User = { id: string; name: string; email: string; role: string; createdAt: string };
const skills = ["READING", "LISTENING", "WRITING", "SPEAKING", "QUANT", "VERBAL"];
const types = ["SINGLE_CHOICE", "MULTI_SELECT", "TRUE_FALSE_NOT_GIVEN", "MATCHING", "GAP_FILL", "NUMERIC_ENTRY", "QUANT_COMPARISON", "ESSAY", "SPEAKING_TASK"];

export function AdminStudio() {
  const router = useRouter(); const [content, setContent] = useState<Exam[]>([]); const [users, setUsers] = useState<User[]>([]); const [tab, setTab] = useState("inventory"); const [message, setMessage] = useState("Loading content…");
  const load = useCallback(async () => { try { const [catalog, people] = await Promise.all([api<Exam[]>("/admin/content"), api<User[]>("/admin/users").catch(() => [])]); setContent(catalog); setUsers(people); setMessage(""); } catch (e) { const err = e as Error & { status?: number }; if (err.status === 401) router.push("/login"); else setMessage(err.status === 403 ? "Administrator or content-editor access is required." : err.message); } }, [router]);
  useEffect(() => { void load(); }, [load]);
  const sections = useMemo(() => content.flatMap((exam) => exam.sections.map((section) => ({ ...section, examId: exam.id, examName: exam.name }))), [content]);
  async function submit(path: string, payload: unknown) { setMessage("Saving…"); try { await api(path, { method: "POST", body: JSON.stringify(payload) }); setMessage("Saved."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Save failed."); } }
  if (!content.length && message) return <div className="loading-screen"><span className="instrument-mini">ADMIN · LOCKED</span><p>{message}</p></div>;
  return <div className="admin"><header className="page-heading"><div><div className="eyebrow">CONTENT OPERATIONS</div><h1>Content studio</h1><p>Author original material, assemble versioned forms, and inspect the delivery inventory.</p></div><div className="time-stat"><small>PUBLISHED FORMS</small><strong>{String(content.reduce((n, exam) => n + exam.testForms.filter((f) => f.isPublished).length, 0)).padStart(2, "0")}</strong><span>candidate-ready</span></div></header><nav className="tabs" aria-label="Content studio sections">{["inventory", "section", "passage", "question", "form", "media", "import", "preview", "flags", "analytics", "users"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>{message && <div className="status-line" role="status">{message}</div>}{tab === "inventory" && <Inventory content={content}/>} {tab === "section" && <SectionForm exams={content} onSubmit={(payload) => submit("/admin/sections", payload)}/>} {tab === "passage" && <PassageForm sections={sections} onSubmit={(payload) => submit("/admin/passages", payload)}/>} {tab === "question" && <QuestionForm sections={sections} onSubmit={(payload) => submit("/admin/questions", payload)}/>} {tab === "form" && <TestForm exams={content} sections={sections} onSubmit={(payload) => submit("/admin/test-forms", payload)}/>} {tab === "media" && <MediaForm sections={sections} onDone={load} setMessage={setMessage}/>} {tab === "import" && <ImportPanel setMessage={setMessage} onDone={load}/>} {tab === "preview" && <PreviewPanel content={content}/>} {tab === "flags" && <FlagsPanel exams={content} setMessage={setMessage}/>} {tab === "analytics" && <AnalyticsPanel/>} {tab === "users" && <Users users={users} onDone={load} setMessage={setMessage}/>}</div>;
}

function Inventory({ content }: { content: Exam[] }) { return <section className="admin-panel"><div className="section-title"><div><span>01</span><h2>Content inventory</h2></div><p>Published attempts lock their version</p></div>{content.map((exam) => <details className="inventory-exam" key={exam.id} open><summary><div><b>{exam.name}</b><span>{exam.code}</span></div><div>{exam.sections.length} sections · {exam.testForms.length} forms</div></summary><div className="inventory-grid"><div><h3>Sections</h3>{exam.sections.map((section) => <div className="inventory-row" key={section.id}><span><b>{section.name}</b><small>{section.skill} · {Math.ceil(section.timeLimitSec / 60)} min</small></span><span>{section.questions.length} questions</span></div>)}</div><div><h3>Test forms</h3>{exam.testForms.map((form) => <div className="inventory-row" key={form.id}><span><b>{form.name}</b><small>Version {form.version}</small></span><span className={form.isPublished ? "published" : "draft"}>{form.isPublished ? "Published" : "Draft"} · {form._count.sessions} attempts</span></div>)}</div></div></details>)}</section>; }

function StudioForm({ title, note, children, onSubmit }: { title: string; note: string; children: React.ReactNode; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <section className="admin-panel editor-panel"><div><div className="eyebrow">AUTHORING</div><h2>{title}</h2><p>{note}</p></div><form className="studio-form" onSubmit={onSubmit}>{children}<button className="button primary">Save to content bank</button></form></section>; }
function SectionForm({ exams, onSubmit }: { exams: Exam[]; onSubmit: (v: unknown) => void }) {
  return <StudioForm title="New section" note="Set the server-authoritative time limit, skill, and adaptive difficulty before adding source material." onSubmit={(e) => {
    e.preventDefault(); const f = new FormData(e.currentTarget);
    onSubmit({ examId: f.get("examId"), name: f.get("name"), order: Number(f.get("order")), timeLimitSec: Number(f.get("minutes")) * 60, skill: f.get("skill"), difficultyLevel: Number(f.get("difficultyLevel")), instructions: f.get("instructions") });
  }}><label>Exam<select name="examId" required>{exams.map((e) => <option value={e.id} key={e.id}>{e.name}</option>)}</select></label><div className="form-grid"><label>Section name<input name="name" required/></label><label>Order<input name="order" type="number" min="1" defaultValue="1" required/></label></div><div className="form-grid"><label>Time limit (minutes)<input name="minutes" type="number" min="1" defaultValue="20" required/></label><label>Skill<select name="skill">{skills.map((s) => <option key={s}>{s}</option>)}</select></label></div><label>Difficulty level<input name="difficultyLevel" type="number" min="1" defaultValue="1"/></label><label>Candidate instructions<textarea name="instructions" rows={4}/></label></StudioForm>;
}
function PassageForm({ sections, onSubmit }: { sections: Array<Section & { examName: string }>; onSubmit: (v: unknown) => void }) { return <StudioForm title="New passage" note="Use original text only. Paragraph breaks are preserved in the candidate view." onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); onSubmit(Object.fromEntries(f)); }}><label>Section<select name="sectionId" required>{sections.map((s) => <option value={s.id} key={s.id}>{s.examName} · {s.name}</option>)}</select></label><label>Passage title<input name="title" required/></label><label>Passage text<textarea className="rich-source" name="bodyRichtext" rows={14} required/></label><label>Source note<input name="sourceNote" placeholder="Original content written for this platform."/></label></StudioForm>; }
function QuestionForm({ sections, onSubmit }: { sections: Array<Section & { examName: string }>; onSubmit: (v: unknown) => void }) { return <StudioForm title="New question" note="For options, enter one line per option as label|value. Accepted answers use comma-separated option values." onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const strategy = String(f.get("strategy")); const accepted = String(f.get("answers")).split(",").map((v) => v.trim()).filter(Boolean); const options = String(f.get("options") ?? "").split("\n").map((line) => line.trim()).filter(Boolean).map((line, i) => { const [rawLabel, rawValue] = line.split("|"); const label = rawLabel?.trim() || String(i + 1); const value = rawValue?.trim() || label; return { label, value, order: i + 1, isCorrect: accepted.includes(value) }; }); onSubmit({ sectionId: f.get("sectionId"), passageId: f.get("passageId") || undefined, type: f.get("type"), prompt: f.get("prompt"), order: Number(f.get("order")), points: Number(f.get("points")), metadata: f.get("minimumWords") ? { minimumWords: Number(f.get("minimumWords")) } : undefined, options, answerKey: { acceptedAnswers: accepted, matchStrategy: strategy, tolerance: strategy === "NUMERIC_TOLERANCE" ? Number(f.get("tolerance")) : undefined } }); }}><label>Section<select name="sectionId" required>{sections.map((s) => <option value={s.id} key={s.id}>{s.examName} · {s.name}</option>)}</select></label><label>Passage (optional)<select name="passageId"><option value="">No passage</option>{sections.flatMap((s) => s.passages.map((p) => <option value={p.id} key={p.id}>{s.name} · {p.title}</option>))}</select></label><div className="form-grid"><label>Question type<select name="type">{types.map((t) => <option key={t}>{t}</option>)}</select></label><label>Order<input name="order" type="number" min="1" defaultValue="1" required/></label></div><label>Prompt<textarea name="prompt" rows={4} required/></label><label>Options<textarea name="options" rows={5} placeholder={"A|First option\nB|Second option"}/></label><div className="form-grid"><label>Accepted answer(s)<input name="answers" placeholder="A, C"/></label><label>Match strategy<select name="strategy"><option>EXACT</option><option>CASE_INSENSITIVE</option><option>LEMMATIZED</option><option>NUMERIC_TOLERANCE</option><option>MULTI_EXACT</option><option>MULTI_PARTIAL</option><option>MANUAL</option><option>AI</option></select></label></div><div className="form-grid"><label>Points<input name="points" type="number" min="0" step="0.5" defaultValue="1"/></label><label>Numeric tolerance<input name="tolerance" type="number" min="0" step="0.001" defaultValue="0"/></label></div><label>Minimum words (writing only)<input name="minimumWords" type="number" min="0"/></label></StudioForm>; }
function TestForm({ exams, sections, onSubmit }: { exams: Exam[]; sections: Array<Section & { examId: string; examName: string }>; onSubmit: (v: unknown) => void }) {
  return <StudioForm title="Assemble test form" note="A published form becomes immutable after its first candidate attempt. Adaptive stages may share an order and use score ranges." onSubmit={(e) => {
    e.preventDefault(); const f = new FormData(e.currentTarget); const sectionIds = f.getAll("sections").map(String);
    const rules = String(f.get("routeRules") ?? "").split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [sectionId, order, minimum, maximum] = line.split("|").map((value) => value.trim()); return { sectionId, order: Number(order), routeMinPercent: minimum === "" ? undefined : Number(minimum), routeMaxPercent: maximum === "" ? undefined : Number(maximum) }; });
    onSubmit({ examId: f.get("examId"), name: f.get("name"), slug: f.get("slug"), version: Number(f.get("version")), isPublished: f.get("published") === "on", sections: rules.length ? rules : sectionIds.map((sectionId, i) => ({ sectionId, order: i + 1 })) });
  }}><label>Exam<select name="examId">{exams.map((e) => <option value={e.id} key={e.id}>{e.name}</option>)}</select></label><div className="form-grid"><label>Form name<input name="name" required/></label><label>URL slug<input name="slug" pattern="[a-z0-9-]+" required/></label></div><label>Sections<select name="sections" multiple size={Math.min(8, Math.max(3, sections.length))}>{sections.map((s) => <option value={s.id} key={s.id}>{s.examName} · {s.name}</option>)}</select><small>Use Ctrl/Cmd to select a simple linear form.</small></label><label>Adaptive route rules (optional)<textarea name="routeRules" rows={5} placeholder="section-id|order|min-percent|max-percent"/><small>One route per line. Leave a boundary empty for an open range; stages at the same order are alternatives.</small></label><div className="form-grid"><label>Version<input name="version" type="number" min="1" defaultValue="1"/></label><label className="check"><input name="published" type="checkbox"/> Publish for candidates</label></div></StudioForm>;
}
function MediaForm({ sections, onDone, setMessage }: { sections: Array<Section & { examName: string }>; onDone: () => void; setMessage: (s: string) => void }) { return <StudioForm title="Upload audio or image" note="The browser uploads directly to S3-compatible storage using a short-lived URL." onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const file = f.get("file") as File; try { setMessage("Uploading…"); const ticket = await api<{ key: string; uploadUrl: string }>("/media/upload", { method: "POST", body: JSON.stringify({ filename: file.name.replace(/[^\w.-]/g, "-"), contentType: file.type || "application/octet-stream" }) }); const uploaded = await fetch(ticket.uploadUrl, { method: "PUT", headers: { "content-type": file.type || "application/octet-stream" }, body: file }); if (!uploaded.ok) throw new Error("Storage rejected the upload."); if (file.type.startsWith("audio/")) await api("/admin/audio-assets", { method: "POST", body: JSON.stringify({ sectionId: f.get("sectionId"), storageKey: ticket.key, durationSec: Number(f.get("durationSec")), transcript: f.get("transcript") }) }); setMessage("Upload complete."); onDone(); } catch (err) { setMessage(err instanceof Error ? err.message : "Upload failed."); } }}><label>Section<select name="sectionId">{sections.map((s) => <option value={s.id} key={s.id}>{s.examName} · {s.name}</option>)}</select></label><label>File<input name="file" type="file" accept="audio/*,image/*" required/></label><label>Audio duration (seconds)<input name="durationSec" type="number" min="1" defaultValue="60"/></label><label>Transcript (hidden until review)<textarea name="transcript" rows={8}/></label></StudioForm>; }
function Users({ users, onDone, setMessage }: { users: User[]; onDone: () => void; setMessage: (s: string) => void }) { return <section className="admin-panel"><div className="section-title"><div><span>07</span><h2>User roles</h2></div><p>Admin only</p></div><div className="user-table">{users.map((user) => <div key={user.id}><span><b>{user.name}</b><small>{user.email}</small></span><select value={user.role} onChange={async (e) => { try { await api(`/admin/users/${user.id}/role`, { method: "PATCH", body: JSON.stringify({ role: e.target.value }) }); setMessage("Role updated."); onDone(); } catch (err) { setMessage(err instanceof Error ? err.message : "Role update failed."); } }}><option>STUDENT</option><option>CONTENT_EDITOR</option><option>ADMIN</option></select><time>{new Date(user.createdAt).toLocaleDateString()}</time></div>)}</div></section>; }

function ImportPanel({ setMessage, onDone }: { setMessage: (value: string) => void; onDone: () => void }) { return <StudioForm title="Bulk JSON import" note="Paste a validated object with a questions array. Each result reports its source index and any error without discarding successful rows." onSubmit={async (event) => { event.preventDefault(); const raw = String(new FormData(event.currentTarget).get("json")); try { const payload = JSON.parse(raw); const result = await api<{ imported: number; failed: number }>("/admin/import", { method: "POST", body: JSON.stringify(payload) }); setMessage(`Imported ${result.imported}; ${result.failed} failed.`); onDone(); } catch (error) { setMessage(error instanceof Error ? error.message : "Import failed."); } }}><label>Import JSON<textarea name="json" rows={18} spellCheck={false} defaultValue={'{\n  "questions": []\n}'}/></label></StudioForm>; }

function PreviewPanel({ content }: { content: Exam[] }) { const [selected,setSelected]=useState(""); const forms=content.flatMap((exam)=>exam.testForms.map((form)=>({exam,form}))); const current=forms.find((item)=>item.form.id===selected)??forms[0]; return <section className="admin-panel"><div className="section-title"><div><span>08</span><h2>Candidate preview</h2></div><p>No attempt is created</p></div><label className="preview-select">Test form<select value={current?.form.id??""} onChange={(event)=>setSelected(event.target.value)}>{forms.map(({exam,form})=><option value={form.id} key={form.id}>{exam.name} · {form.name}</option>)}</select></label>{current&&<div className="candidate-preview"><header><div className="eyebrow">{current.exam.code} · VERSION {current.form.version}</div><h2>{current.form.name}</h2></header>{current.form.sections.sort((a,b)=>a.order-b.order).map((link)=>{const section=current.exam.sections.find((item)=>item.id===link.sectionId);return section?<article key={section.id}><span className="instrument-mini">SECTION {link.order} · {Math.ceil(section.timeLimitSec/60)} MIN</span><h3>{section.name}</h3>{section.passages.map((item)=><p key={item.id}>{item.title}</p>)}<ol>{section.questions.map((item)=><li key={item.id}>{item.prompt}<small>{item.type.code.replaceAll("_"," ")}</small></li>)}</ol></article>:null})}</div>}</section>; }

type FeatureFlag = { id:string; key:string; enabled:boolean; examId?:string; exam?:{name:string} };
function FlagsPanel({ exams, setMessage }: { exams: Exam[]; setMessage: (value:string)=>void }) { const [flags,setFlags]=useState<FeatureFlag[]>([]); const refresh=useCallback(()=>{void api<FeatureFlag[]>("/admin/feature-flags").then(setFlags)},[]); useEffect(refresh,[refresh]); async function update(key:string,enabled:boolean,examId?:string){try{await api("/admin/feature-flags",{method:"POST",body:JSON.stringify({key,enabled,examId})});setMessage("Feature flag updated.");refresh();}catch(error){setMessage(error instanceof Error?error.message:"Update failed.")}} return <section className="admin-panel"><div className="section-title"><div><span>09</span><h2>Feature flags</h2></div><p>Global defaults and exam overrides</p></div><div className="flag-grid">{["AI_SCORING","TRANSCRIPTION"].map((key)=>{const global=flags.find((item)=>item.key===key&&!item.examId);return <article key={key}><h3>{key.replaceAll("_"," ")}</h3><label className="check"><input type="checkbox" checked={global?.enabled??false} onChange={(event)=>update(key,event.target.checked)}/> Global</label>{exams.map((exam)=>{const flag=flags.find((item)=>item.key===key&&item.examId===exam.id);return <label className="check" key={exam.id}><input type="checkbox" checked={flag?.enabled??global?.enabled??false} onChange={(event)=>update(key,event.target.checked,exam.id)}/>{exam.name}</label>})}</article>})}</div></section>; }

type Analytics = { items:Array<{id:string;prompt:string;type:string;attempts:number;percentCorrect:number|null;discrimination:number|null;flaggedAsUnclear:number}>; funnel:{started:number;completed:number;completionRate:number}; timing:{averageSectionSeconds:number} };
function AnalyticsPanel(){const [data,setData]=useState<Analytics>();useEffect(()=>{void api<Analytics>("/admin/analytics/questions").then(setData)},[]);if(!data)return <div className="loading-screen"><span className="instrument-mini">ANALYTICS · SYNC</span></div>;return <section className="admin-panel"><div className="score-grid"><div className="score-card quiet"><small>STARTED</small><strong>{data.funnel.started}</strong><span>sessions</span></div><div className="score-card quiet"><small>COMPLETED</small><strong>{Math.round(data.funnel.completionRate*100)}%</strong><span>{data.funnel.completed} submitted</span></div><div className="score-card quiet"><small>AVG SECTION</small><strong>{Math.round(data.timing.averageSectionSeconds/60)}m</strong><span>elapsed time</span></div></div><div className="history-table"><div className="history-head"><span>Question</span><span>Type</span><span>Accuracy</span><span>Disc. / unclear</span></div>{data.items.map((item)=><div className="history-row" key={item.id}><span>{item.prompt}</span><span>{item.type.replaceAll("_"," ")}</span><span className="mono">{item.percentCorrect==null?"—":`${Math.round(item.percentCorrect*100)}%`}</span><span className="mono">{item.discrimination==null?"—":item.discrimination.toFixed(2)} / {item.flaggedAsUnclear}</span></div>)}</div></section>}
