"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";

type CatalogExam = { id: string; code: string; name: string; description: string; testForms: Array<{ id: string; name: string; version: number; sections: Array<{ section: { timeLimitSec: number } }> }> };
type Progress = { history: Array<{ id: string; exam: string; form: string; submittedAt: string; scores: Array<{ skill: string; rawScore: number; maxScore: number; band?: number; scaledScore?: number }> }>; weakAreas: Array<{ type: string; accuracy: number; total: number }> };

export function Dashboard() {
  const router = useRouter(); const [catalog, setCatalog] = useState<CatalogExam[]>([]); const [progress, setProgress] = useState<Progress>({ history: [], weakAreas: [] }); const [error, setError] = useState(""); const [starting, setStarting] = useState("");
  useEffect(() => { Promise.all([api<CatalogExam[]>("/exams"), api<Progress>("/me/progress")]).then(([a, b]) => { setCatalog(a); setProgress(b); }).catch((e: Error & { status?: number }) => { if (e.status === 401) router.push("/login"); else setError(e.message); }); }, [router]);
  async function start(testFormId: string) { setStarting(testFormId); try { const session = await api<{ id: string }>("/sessions", { method: "POST", body: JSON.stringify({ testFormId }) }); router.push(`/test/${session.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Test could not start."); setStarting(""); } }
  return <div className="dashboard"><header className="page-heading"><div><div className="eyebrow">CANDIDATE WORKSPACE</div><h1>Your practice signal</h1><p>Start a timed form or inspect the evidence from earlier attempts.</p></div><div className="time-stat"><small>COMPLETED</small><strong>{String(progress.history.length).padStart(2, "0")}</strong><span>full attempts</span></div></header>{error && <div className="error" role="alert">{error}</div>}<section><div className="section-title"><div><span>01</span><h2>Available forms</h2></div><p>Published, original practice content</p></div><div className="exam-cards">{catalog.map((exam) => <article className="exam-card" key={exam.id}><div className="exam-code">{exam.code.replace("_", " · ")}</div><h3>{exam.name}</h3><p>{exam.description}</p>{exam.testForms.length ? exam.testForms.map((form) => { const mins = Math.ceil(form.sections.reduce((n, s) => n + s.section.timeLimitSec, 0) / 60); return <div className="form-row" key={form.id}><div><b>{form.name}</b><span>v{form.version} · {mins} min</span></div><button className="button compact" onClick={() => start(form.id)} disabled={!!starting}>{starting === form.id ? "Starting…" : "Start test"}</button></div>; }) : <div className="empty-inline">No published form yet.</div>}</article>)}</div></section><section><div className="section-title"><div><span>02</span><h2>Score history</h2></div><p>Oldest to newest</p></div>{progress.history.length ? <div className="history-table" role="table"><div className="history-head" role="row"><span>Attempt</span><span>Skill</span><span>Score</span><span>Date</span></div>{progress.history.flatMap((item) => item.scores.map((score) => <button key={`${item.id}-${score.skill}`} className="history-row" onClick={() => router.push(`/results/${item.id}`)}><span><b>{item.exam}</b><small>{item.form}</small></span><span>{score.skill}</span><span className="mono">{score.band ? `Band ${score.band}` : score.scaledScore ?? `${score.rawScore}/${score.maxScore}`}</span><time>{new Date(item.submittedAt).toLocaleDateString()}</time></button>))}</div> : <div className="empty-state"><span className="instrument-mini">NO DATA · --:--</span><h3>Your baseline starts with one completed form.</h3><p>Choose a published practice test above. Answers are saved as you work.</p></div>}</section><section><div className="section-title"><div><span>03</span><h2>Weak-area readout</h2></div><p>Accuracy by question type</p></div><div className="weak-grid">{progress.weakAreas.length ? progress.weakAreas.map((area) => <div className="weak-item" key={area.type}><div><b>{area.type.replaceAll("_", " ")}</b><span>{area.total} attempts</span></div><strong>{Math.round(area.accuracy * 100)}%</strong><div className="meter"><i style={{ width: `${area.accuracy * 100}%` }}/></div></div>) : <p className="muted">Weak-area analysis appears after your first scored attempt.</p>}</div></section></div>;
}
