"use client";
import { useEffect, useRef, useState } from "react";
import { api } from "@/lib/api";

type Question = { id: string; type: { code: string }; prompt: string; metadata?: Record<string, unknown>; options: Array<{ id: string; label: string; value: string }> };
export function QuestionInput({ question, value, onChange, sessionId }: { question: Question; value: unknown; onChange: (value: unknown) => void; sessionId: string }) {
  const current = (value as { value?: unknown } | undefined)?.value;
  if (["SINGLE_CHOICE", "TRUE_FALSE_NOT_GIVEN", "QUANT_COMPARISON"].includes(question.type.code)) return <div className="options">{question.options.map((option) => <label className={`option ${current === option.value ? "selected" : ""}`} key={option.id}><input type="radio" name={question.id} value={option.value} checked={current === option.value} onChange={() => onChange({ value: option.value })}/><b>{option.label}</b><span>{option.value === option.label ? option.label.replaceAll("_", " ") : option.value}</span></label>)}</div>;
  if (["MULTI_SELECT", "MATCHING"].includes(question.type.code)) { const selected = Array.isArray(current) ? current as string[] : []; return <div className="options">{question.options.map((option) => <label className={`option ${selected.includes(option.value) ? "selected" : ""}`} key={option.id}><input type="checkbox" checked={selected.includes(option.value)} onChange={() => onChange({ value: selected.includes(option.value) ? selected.filter((v) => v !== option.value) : [...selected, option.value] })}/><b>{option.label}</b><span>{option.value === option.label ? option.label : option.value}</span></label>)}</div>; }
  if (question.type.code === "ESSAY") { const text = String((value as { text?: string } | undefined)?.text ?? ""); const words = text.trim() ? text.trim().split(/\s+/).length : 0; const minimum = Number(question.metadata?.minimumWords ?? 250); return <><textarea className="essay-editor" value={text} onPaste={(e) => e.preventDefault()} onChange={(e) => onChange({ text: e.target.value })} aria-label="Essay response"/><div className={`word-count ${words < minimum ? "under" : ""}`}><span>{words} words</span><span>Suggested minimum: {minimum}</span></div></>; }
  if (question.type.code === "SPEAKING_TASK") return <SpeakingInput sessionId={sessionId} metadata={question.metadata} onChange={onChange}/>;
  return <label className="short-answer"><span>{question.type.code === "NUMERIC_ENTRY" ? "Enter a number" : "Your answer"}</span><input inputMode={question.type.code === "NUMERIC_ENTRY" ? "decimal" : "text"} value={String(current ?? "")} onChange={(e) => onChange({ value: e.target.value })}/></label>;
}

function SpeakingInput({ onChange, sessionId, metadata }: { onChange: (value: unknown) => void; sessionId: string; metadata?: Record<string, unknown> }) {
  const prepSeconds = Number(metadata?.prepSeconds ?? 30); const responseSeconds = Number(metadata?.responseSeconds ?? 60); const [phase, setPhase] = useState<"idle"|"prep"|"recording"|"uploading"|"done">("idle"); const [remaining, setRemaining] = useState(prepSeconds); const recorder = useRef<MediaRecorder | null>(null); const stopped = useRef(false);
  useEffect(() => { if (phase !== "prep" && phase !== "recording") return; const id = window.setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(id); }, [phase]);
  useEffect(() => { if (remaining !== 0) return; if (phase === "prep") void record(); else if (phase === "recording" && !stopped.current) { stopped.current = true; recorder.current?.stop(); } }, [remaining, phase]);
  function begin() { setRemaining(prepSeconds); setPhase("prep"); }
  async function record() {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const chunks: Blob[] = []; const mediaRecorder = new MediaRecorder(stream); recorder.current = mediaRecorder; stopped.current = false;
    mediaRecorder.ondataavailable = (event) => chunks.push(event.data); mediaRecorder.onstop = async () => { setPhase("uploading"); const blob = new Blob(chunks, { type: mediaRecorder.mimeType }); stream.getTracks().forEach((track) => track.stop()); try { const ticket = await api<{ key: string; uploadUrl: string }>(`/media/sessions/${sessionId}/response-upload`, { method: "POST", body: JSON.stringify({ filename: "speaking.webm", contentType: blob.type || "audio/webm" }) }); const uploaded = await fetch(ticket.uploadUrl, { method: "PUT", headers: { "content-type": blob.type || "audio/webm" }, body: blob }); if (!uploaded.ok) throw new Error("Audio upload failed."); onChange({ audioKey: ticket.key }); setPhase("done"); } catch { setPhase("idle"); } };
    setRemaining(responseSeconds); setPhase("recording"); mediaRecorder.start();
  }
  return <div className="recorder"><div className="waveform" aria-hidden="true">{Array.from({ length: 28 }, (_, i) => <i key={i} style={{ height: `${18 + ((i * 17) % 46)}%` }}/>)}</div><div className="speaking-phase"><b>{phase === "prep" ? "PREPARATION" : phase === "recording" ? "RESPONSE" : phase.toUpperCase()}</b>{(phase === "prep" || phase === "recording") && <strong>{remaining}s</strong>}</div><div>{phase === "idle" && <button className="button secondary" type="button" onClick={begin}>Begin preparation</button>}{phase === "prep" && <button className="button secondary" type="button" onClick={record}>Start response now</button>}{phase === "recording" && <button className="button text-button" type="button" onClick={() => { stopped.current = true; recorder.current?.stop(); }}>Stop response</button>}</div><p>{phase === "done" ? "Response uploaded and saved with this answer." : phase === "uploading" ? "Uploading response…" : `${prepSeconds}s preparation · ${responseSeconds}s response`}</p></div>;
}
