"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { Calculator } from "./calculator";
import { QuestionInput } from "./question-input";
import { SecureAudio } from "./secure-audio";
import { Timer } from "./timer";

type Question = { id: string; prompt: string; order: number; type: { code: string }; metadata?: Record<string, unknown>; options: Array<{ id: string; label: string; value: string }> };
type Section = { id: string; name: string; skill: string; timeLimitSec: number; instructions?: string; passages: Array<{ id: string; title: string; bodyRichtext: string }>; audioAssets: Array<{ id: string; storageKey: string; durationSec: number }>; questions: Question[] };
type Session = { id: string; status: string; activeSectionId: string; endsAt: string; integrityEventCount: number; answers: Array<{ questionId: string; response: unknown; flagged: boolean }>; form: { name: string; exam: { name: string; code: string }; sections: Array<{ order: number; section: Section }> } };

export function TestRunner({ sessionId }: { sessionId: string }) {
  const router = useRouter(); const [session, setSession] = useState<Session>(); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<string, unknown>>({}); const [flags, setFlags] = useState<Record<string, boolean>>({}); const [notes, setNotes] = useState(""); const [message, setMessage] = useState("Loading test…");
  const timers = useRef<Record<string, ReturnType<typeof setTimeout>>>({}); const pending = useRef<Record<string, { response: unknown; flagged: boolean }>>({}); const leaving = useRef(false);
  const load = useCallback(async () => { try { const data = await api<Session>(`/sessions/${sessionId}`); if (["SCORED", "MANUAL_REVIEW", "SUBMITTED"].includes(data.status)) return router.replace(`/results/${sessionId}`); setSession(data); setAnswers(Object.fromEntries(data.answers.map((a) => [a.questionId, a.response]))); setFlags(Object.fromEntries(data.answers.map((a) => [a.questionId, a.flagged]))); setMessage(""); } catch (e) { setMessage(e instanceof Error ? e.message : "The test could not be loaded."); } }, [router, sessionId]);
  useEffect(() => { void load(); }, [load]);
  const active = session?.form.sections.find((item) => item.section.id === session.activeSectionId)?.section; const question = active?.questions[index];
  useEffect(() => { if (active && index >= active.questions.length) setIndex(0); }, [active, index]);
  const log = useCallback((type: string, detail?: Record<string, unknown>) => { if (!leaving.current) void api(`/sessions/${sessionId}/integrity`, { method: "POST", body: JSON.stringify({ type, detail }) }).catch(() => undefined); }, [sessionId]);
  useEffect(() => { const visibility = () => document.hidden && log("visibility_hidden"); const blur = () => log("window_blur"); const fullscreen = () => !document.fullscreenElement && log("fullscreen_exit"); document.addEventListener("visibilitychange", visibility); document.addEventListener("fullscreenchange", fullscreen); window.addEventListener("blur", blur); return () => { document.removeEventListener("visibilitychange", visibility); document.removeEventListener("fullscreenchange", fullscreen); window.removeEventListener("blur", blur); }; }, [log]);
  function save(qid: string, response: unknown, flagged = flags[qid] ?? false) { setAnswers((v) => ({ ...v, [qid]: response })); pending.current[qid] = { response, flagged }; clearTimeout(timers.current[qid]); timers.current[qid] = setTimeout(() => void api(`/sessions/${sessionId}/answers/${qid}`, { method: "PATCH", body: JSON.stringify({ response, flagged }) }).then(() => { delete pending.current[qid]; }).catch((e: Error) => setMessage(e.message)), 500); }
  function flag() { if (!question) return; const next = !flags[question.id]; setFlags((v) => ({ ...v, [question.id]: next })); save(question.id, answers[question.id] ?? {}, next); }
  function reportUnclear() { if (!question) return; log("question_unclear", { questionId: question.id }); setMessage("Thank you. This item was reported to the content team."); }
  const finishSection = useCallback(async () => { if (!active || leaving.current) return; leaving.current = true; setMessage("Submitting section…"); try { Object.values(timers.current).forEach(clearTimeout); const unsaved = Object.entries(pending.current); await Promise.all(unsaved.map(([qid, payload]) => api(`/sessions/${sessionId}/answers/${qid}`, { method: "PATCH", body: JSON.stringify(payload) }))); pending.current = {}; const result = await api<{ status?: string }>(`/sessions/${sessionId}/sections/${active.id}/submit`, { method: "POST" }); if (["SCORED", "MANUAL_REVIEW", "SUBMITTED"].includes(result?.status ?? "")) router.replace(`/results/${sessionId}`); else { leaving.current = false; setIndex(0); await load(); } } catch (e) { leaving.current = false; setMessage(e instanceof Error ? e.message : "Section submission failed."); } }, [active, load, router, sessionId]);
  function highlight() { const selection = window.getSelection(); if (!selection?.rangeCount || selection.isCollapsed) return; const range = selection.getRangeAt(0); const mark = document.createElement("mark"); try { range.surroundContents(mark); selection.removeAllRanges(); } catch { setMessage("Select text within one paragraph to highlight it."); } }
  if (!session || !active || !question) return <div className="loading-screen"><span className="instrument-mini">SYNC · --:--</span><p>{message}</p></div>;
  const answered = active.questions.filter((item) => answers[item.id] !== undefined).length;
  return <div className="test-shell">
    <header className="test-bar"><div><small>{session.form.exam.name}</small><strong>{active.name}</strong></div><div className="question-progress"><span>QUESTION</span><b>{String(index + 1).padStart(2, "0")} / {String(active.questions.length).padStart(2, "0")}</b></div><Timer endsAt={session.endsAt} totalSeconds={active.timeLimitSec} onExpire={finishSection}/><button className="fullscreen-button" onClick={() => document.documentElement.requestFullscreen?.()}>Enter fullscreen</button></header>
    {message && <div className="test-message" role="status">{message}</div>}
    <div className={`test-workspace ${active.skill === "READING" || active.skill === "LISTENING" ? "split" : "focused"}`}>
      <section className="source-pane">
        {active.skill === "READING" && <><div className="pane-tools"><span>PASSAGE</span><button onClick={highlight}>Highlight selection</button></div>{active.passages.map((passage) => <article className="passage" key={passage.id}><h1>{passage.title}</h1>{passage.bodyRichtext.split("\n").map((paragraph, i) => <p key={i}>{paragraph}</p>)}</article>)}</>}
        {active.skill === "LISTENING" && <><div className="pane-tools"><span>LISTENING SOURCE</span><b>ONE PLAY</b></div>{active.audioAssets.map((audio) => <SecureAudio key={audio.id} sessionId={sessionId} audioId={audio.id}/>) }<label className="notes"><span>Private notes</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)}/></label></>}
        {["QUANT", "VERBAL"].includes(active.skill) && <><div className="pane-tools"><span>{active.skill} TOOLS</span></div>{active.skill === "QUANT" && <Calculator/>}<p className="instructions">{active.instructions}</p></>}
        {["WRITING", "SPEAKING"].includes(active.skill) && <div className="task-context"><div className="eyebrow">TASK INSTRUCTIONS</div><p>{active.instructions}</p></div>}
      </section>
      <section className="question-pane"><div className="question-number">{String(question.order).padStart(2, "0")}</div><h2>{question.prompt}</h2><QuestionInput sessionId={sessionId} question={question} value={answers[question.id]} onChange={(value) => save(question.id, value)}/><div className="question-actions"><div><button className={`flag ${flags[question.id] ? "active" : ""}`} onClick={flag}>{flags[question.id] ? "Flagged for review" : "Flag for review"}</button><button className="flag" onClick={reportUnclear}>Report unclear</button></div><div><button className="button secondary compact" disabled={index === 0} onClick={() => setIndex((value) => value - 1)}>Previous</button>{index < active.questions.length - 1 ? <button className="button primary compact" onClick={() => setIndex((value) => value + 1)}>Next</button> : <button className="button urgent compact" onClick={finishSection}>Submit section</button>}</div></div></section>
    </div>
    <nav className="question-dock" aria-label="Question navigation"><span>{answered} of {active.questions.length} answered</span><div>{active.questions.map((item, i) => <button key={item.id} className={`${i === index ? "current" : ""} ${answers[item.id] !== undefined ? "answered" : ""} ${flags[item.id] ? "flagged" : ""}`} onClick={() => setIndex(i)} aria-label={`Question ${i + 1}${flags[item.id] ? ", flagged" : ""}`}>{i + 1}</button>)}</div><span>{session.integrityEventCount} integrity events</span></nav>
  </div>;
}
