import { CreateBucketCommand, HeadBucketCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { Exam, ExamCode, MatchStrategy, PrismaClient, QuestionTypeCode, Role, Section, Skill } from "@prisma/client";
import { hash } from "bcryptjs";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const prisma = new PrismaClient();
type Option = [string, string];
type QuestionSeed = { type: QuestionTypeCode; prompt: string; answers: unknown[]; strategy: MatchStrategy; options?: Option[]; tolerance?: number; metadata?: Record<string, unknown>; passageId?: string; audioAssetId?: string; points?: number };
const bands: Array<[number, number, number, number, number]> = [[39,40,9,9,9],[37,38,8.5,9,8.5],[35,36,8,8.5,8],[32,34,7.5,8,7.5],[30,31,7,7.5,7],[26,29,6.5,7,6.5],[23,25,6,6.5,6],[18,22,5.5,6,5.5],[16,17,5,5.5,5],[13,15,4.5,5,4.5],[10,12,4,4,4],[0,9,3.5,3.5,3.5]];

async function exam(code: ExamCode, name: string, description: string) { return prisma.exam.upsert({ where: { code }, update: { name, description }, create: { code, name, description } }); }
async function section(owner: Exam, name: string, order: number, timeLimitSec: number, skill: Skill, instructions: string, difficultyLevel = 1) { return prisma.section.upsert({ where: { examId_name: { examId: owner.id, name } }, update: { order, timeLimitSec, skill, instructions, difficultyLevel }, create: { examId: owner.id, name, order, timeLimitSec, skill, instructions, difficultyLevel } }); }
async function passage(owner: Section, id: string, title: string, bodyRichtext: string) { return prisma.passage.upsert({ where: { id }, update: { title, bodyRichtext }, create: { id, sectionId: owner.id, title, bodyRichtext, sourceNote: "Original content written for Measure." } }); }
async function question(owner: Exam, target: Section, order: number, item: QuestionSeed) {
  const type = await prisma.questionType.findUniqueOrThrow({ where: { examId_code: { examId: owner.id, code: item.type } } });
  const record = await prisma.question.upsert({ where: { sectionId_order: { sectionId: target.id, order } }, update: { typeId: type.id, prompt: item.prompt, points: item.points ?? 1, metadata: item.metadata, passageId: item.passageId, audioAssetId: item.audioAssetId }, create: { sectionId: target.id, typeId: type.id, prompt: item.prompt, order, points: item.points ?? 1, metadata: item.metadata, passageId: item.passageId, audioAssetId: item.audioAssetId } });
  await prisma.questionOption.deleteMany({ where: { questionId: record.id } });
  const accepted = item.answers.map(String);
  for (const [index, option] of (item.options ?? []).entries()) await prisma.questionOption.create({ data: { questionId: record.id, label: option[0], value: option[0], order: index + 1, isCorrect: accepted.includes(option[0]) } });
  await prisma.answerKey.upsert({ where: { questionId: record.id }, update: { acceptedAnswers: item.answers, matchStrategy: item.strategy, tolerance: item.tolerance }, create: { questionId: record.id, acceptedAnswers: item.answers, matchStrategy: item.strategy, tolerance: item.tolerance } });
}
async function form(owner: Exam, slug: string, name: string, sections: Array<{ sectionId: string; order: number; routeMinPercent?: number; routeMaxPercent?: number }>) {
  const record = await prisma.testForm.upsert({ where: { slug }, update: { isPublished: true }, create: { examId: owner.id, slug, name, version: 1, isPublished: true } });
  if (await prisma.testSession.count({ where: { testFormId: record.id } }) === 0) { await prisma.testFormSection.deleteMany({ where: { testFormId: record.id } }); await prisma.testFormSection.createMany({ data: sections.map((item) => ({ testFormId: record.id, ...item })) }); }
  return record;
}
function wav(seconds = 3) { const rate = 8000; const count = rate * seconds; const buffer = Buffer.alloc(44 + count * 2); buffer.write("RIFF",0); buffer.writeUInt32LE(36 + count * 2,4); buffer.write("WAVEfmt ",8); buffer.writeUInt32LE(16,16); buffer.writeUInt16LE(1,20); buffer.writeUInt16LE(1,22); buffer.writeUInt32LE(rate,24); buffer.writeUInt32LE(rate*2,28); buffer.writeUInt16LE(2,32); buffer.writeUInt16LE(16,34); buffer.write("data",36); buffer.writeUInt32LE(count*2,40); for(let i=0;i<count;i++) buffer.writeInt16LE(Math.round(Math.sin(i/rate*2*Math.PI*440)*1800),44+i*2); return buffer; }
function spokenWav(transcript: string) {
  const directory = mkdtempSync(join(tmpdir(), "measure-audio-")); const output = join(directory, "prompt.wav");
  try { execFileSync("espeak-ng", ["-s", "145", "-w", output, transcript], { stdio: "ignore" }); return readFileSync(output); }
  catch { return wav(Math.max(3, Math.ceil(transcript.split(/\s+/).length / 2.4))); }
  finally { rmSync(directory, { recursive: true, force: true }); }
}
async function audio(target: Section, id: string, transcript: string) {
  const key = `seed/${id}.wav`; const client = new S3Client({ region: "us-east-1", endpoint: `http://${process.env.MINIO_ENDPOINT ?? "localhost"}:${process.env.MINIO_PORT ?? "9000"}`, forcePathStyle: true, credentials: { accessKeyId: process.env.MINIO_ACCESS_KEY ?? "minioadmin", secretAccessKey: process.env.MINIO_SECRET_KEY ?? "minioadmin" } }); const bucket = process.env.MINIO_BUCKET ?? "exam-media";
  for (let attempt=0;attempt<10;attempt++) { try { await client.send(new HeadBucketCommand({ Bucket: bucket })); break; } catch { try { await client.send(new CreateBucketCommand({ Bucket: bucket })); break; } catch { await new Promise((resolve) => setTimeout(resolve,500)); } } }
  const recording = spokenWav(transcript); const durationSec = Math.max(3, Math.ceil(transcript.split(/\s+/).length / 2.4));
  await client.send(new PutObjectCommand({ Bucket: bucket, Key: key, Body: recording, ContentType: "audio/wav" }));
  return prisma.audioAsset.upsert({ where: { id }, update: { transcript, storageKey: key, durationSec }, create: { id, sectionId: target.id, storageKey: key, durationSec, transcript } });
}

async function seedScales() {
  await prisma.cttBandTable.deleteMany(); await prisma.scaleTable.deleteMany();
  for (const [rawMin,rawMax,academic,general,listening] of bands) await prisma.cttBandTable.createMany({ data: [{ examCode: ExamCode.IELTS_AC, skill: Skill.READING, rawMin, rawMax, band: academic },{ examCode: ExamCode.IELTS_GT, skill: Skill.READING, rawMin, rawMax, band: general },{ examCode: ExamCode.IELTS_AC, skill: Skill.LISTENING, rawMin, rawMax, band: listening },{ examCode: ExamCode.IELTS_GT, skill: Skill.LISTENING, rawMin, rawMax, band: listening }] });
  const toeflBands: Record<"READING"|"LISTENING"|"SPEAKING"|"WRITING", Array<[number,number,number]>> = {
    READING: [[29,30,6],[27,28,5.5],[24,26,5],[22,23,4.5],[18,21,4],[12,17,3.5],[6,11,3],[4,5,2.5],[3,3,2],[2,2,1.5],[0,1,1]],
    LISTENING: [[28,30,6],[26,27,5.5],[22,25,5],[20,21,4.5],[17,19,4],[13,16,3.5],[9,12,3],[6,8,2.5],[4,5,2],[2,3,1.5],[0,1,1]],
    SPEAKING: [[28,30,6],[27,27,5.5],[25,26,5],[23,24,4.5],[20,22,4],[18,19,3.5],[16,17,3],[13,15,2.5],[10,12,2],[5,9,1.5],[0,4,1]],
    WRITING: [[29,30,6],[27,28,5.5],[24,26,5],[21,23,4.5],[17,20,4],[15,16,3.5],[13,14,3],[11,12,2.5],[7,10,2],[3,6,1.5],[0,2,1]],
  };
  for (const [skill, rows] of Object.entries(toeflBands)) for (const [rawMin, rawMax, band] of rows) await prisma.cttBandTable.create({ data: { examCode: ExamCode.TOEFL, skill: skill as Skill, rawMin, rawMax, band } });
  for (const skill of [Skill.READING, Skill.LISTENING]) for (let raw=0;raw<=30;raw++) await prisma.scaleTable.create({ data: { examCode: ExamCode.TOEFL, skill, rawMin: raw, rawMax: raw, scaledScore: raw } });
  for (const skill of [Skill.VERBAL, Skill.QUANT]) for (const [raw, scaledScore] of [[0,130],[1,143],[2,157],[3,170]] as Array<[number,number]>) await prisma.scaleTable.create({ data: { examCode: ExamCode.GRE, skill, rawMin: raw, rawMax: raw, scaledScore } });
}

async function main() {
  const passwordHash = await hash("Practice123!",12);
  await prisma.user.upsert({ where: { email: "admin@exam.local" }, update: {}, create: { email: "admin@exam.local", name: "Platform Admin", passwordHash, role: Role.ADMIN, emailVerifiedAt: new Date() } });
  await prisma.user.upsert({ where: { email: "student@exam.local" }, update: {}, create: { email: "student@exam.local", name: "Demo Student", passwordHash, role: Role.STUDENT, emailVerifiedAt: new Date() } });
  const ac = await exam(ExamCode.IELTS_AC,"IELTS Academic","Academic English practice under timed conditions."); const gt = await exam(ExamCode.IELTS_GT,"IELTS General Training","General Training reading, writing, listening, and speaking practice."); const toefl = await exam(ExamCode.TOEFL,"TOEFL iBT","Integrated academic English practice."); const gre = await exam(ExamCode.GRE,"GRE General Test","Verbal reasoning, quantitative reasoning, and analytical writing practice.");
  for (const owner of [ac,gt,toefl,gre]) for (const code of Object.values(QuestionTypeCode)) await prisma.questionType.upsert({ where: { examId_code: { examId: owner.id, code } }, update: {}, create: { examId: owner.id, code, description: code.toLowerCase().replaceAll("_"," ") } });
  await seedScales(); await prisma.featureFlag.deleteMany({ where: { key: { in: ["AI_SCORING","TRANSCRIPTION"] } } }); await prisma.featureFlag.createMany({ data: [{ key: "AI_SCORING", enabled: false },{ key: "TRANSCRIPTION", enabled: false }] });

  const acRead = await section(ac,"Reading · Urban Ecology",1,3600,Skill.READING,"Read the passage and answer every question."); const acPass = await passage(acRead,"seed-passage-urban-ecology","The Quiet Return of Urban Wetlands","For much of the twentieth century, city planners treated wetlands as wasted space. Marshy ground was drained or covered. Cities are now restoring small wetlands as working infrastructure.\n\nA wetland can hold storm water and release it slowly. It may filter pollutants, cool the surrounding air, and provide habitat. These benefits do not make wetlands a universal solution: they require land and careful maintenance.\n\nThe social results are less automatic. Some projects therefore pair ecological work with long-term affordability rules and community stewardship.");
  await question(ac,acRead,1,{type:QuestionTypeCode.SINGLE_CHOICE,prompt:"Why are cities restoring wetlands?",answers:["B"],strategy:MatchStrategy.EXACT,passageId:acPass.id,options:[["A","Private reserves"],["B","Multi-purpose infrastructure"],["C","Road construction"],["D","Parking"]]}); await question(ac,acRead,2,{type:QuestionTypeCode.TRUE_FALSE_NOT_GIVEN,prompt:"Wetlands can replace every conventional drain.",answers:["FALSE"],strategy:MatchStrategy.EXACT,passageId:acPass.id,options:[["TRUE","True"],["FALSE","False"],["NOT_GIVEN","Not given"]]}); await question(ac,acRead,3,{type:QuestionTypeCode.GAP_FILL,prompt:"Wetlands can hold ____ water.",answers:["storm"],strategy:MatchStrategy.CASE_INSENSITIVE,passageId:acPass.id}); await question(ac,acRead,4,{type:QuestionTypeCode.MULTI_SELECT,prompt:"Select TWO benefits.",answers:["A","C"],strategy:MatchStrategy.MULTI_EXACT,passageId:acPass.id,options:[["A","Filtering pollutants"],["B","Removing maintenance"],["C","Cooling air"],["D","Guaranteeing low rent"]]});
  const acListen = await section(ac,"Listening · Research Briefing",2,1800,Skill.LISTENING,"Play the recording once and answer from your notes."); const acAudio = await audio(acListen,"seed-audio-ac","The research briefing begins in the north library at nine thirty. Participants should bring a pencil and their campus card."); await question(ac,acListen,1,{type:QuestionTypeCode.MATCHING,prompt:"Select the TWO items participants should bring.",answers:["A","C"],strategy:MatchStrategy.MULTI_EXACT,audioAssetId:acAudio.id,options:[["A","Pencil"],["B","Laptop"],["C","Campus card"],["D","Passport"]]}); await question(ac,acListen,2,{type:QuestionTypeCode.GAP_FILL,prompt:"The briefing begins at ____.",answers:["9:30","nine thirty"],strategy:MatchStrategy.CASE_INSENSITIVE,audioAssetId:acAudio.id});
  const acWrite = await section(ac,"Writing · Public Space",3,3600,Skill.WRITING,"Write at least 250 words. Paste is disabled."); await question(ac,acWrite,1,{type:QuestionTypeCode.ESSAY,prompt:"Some cities replace parking spaces with public gardens. Discuss both views and give your position.",answers:[],strategy:MatchStrategy.AI,points:9,metadata:{minimumWords:250}});
  const acSpeak = await section(ac,"Speaking · Community",4,900,Skill.SPEAKING,"Use preparation time, then record one uninterrupted response."); await question(ac,acSpeak,1,{type:QuestionTypeCode.SPEAKING_TASK,prompt:"Describe a public place that is important to your community.",answers:[],strategy:MatchStrategy.AI,points:9,metadata:{prepSeconds:60,responseSeconds:120}});
  await form(ac,"ielts-academic-complete-1","Academic Complete Practice 1",[{sectionId:acRead.id,order:1},{sectionId:acListen.id,order:2},{sectionId:acWrite.id,order:3},{sectionId:acSpeak.id,order:4}]); await form(ac,"ielts-academic-diagnostic-1","Academic Diagnostic 1",[{sectionId:acRead.id,order:1}]);

  const gtRead = await section(gt,"Reading · Community Notice",1,3600,Skill.READING,"Read the notice and answer all questions."); const gtPass = await passage(gtRead,"seed-passage-gt","Shared Workshop Notice","The community workshop opens Tuesday to Saturday. Members reserve tools online and must complete a safety induction before using powered equipment. Weekend classes are included in annual membership, but materials are charged separately."); await question(gt,gtRead,1,{type:QuestionTypeCode.TRUE_FALSE_NOT_GIVEN,prompt:"The workshop opens on Mondays.",answers:["FALSE"],strategy:MatchStrategy.EXACT,passageId:gtPass.id,options:[["TRUE","True"],["FALSE","False"],["NOT_GIVEN","Not given"]]}); await question(gt,gtRead,2,{type:QuestionTypeCode.GAP_FILL,prompt:"Members reserve tools ____.",answers:["online"],strategy:MatchStrategy.CASE_INSENSITIVE,passageId:gtPass.id});
  const gtListen = await section(gt,"Listening · Service Call",2,1800,Skill.LISTENING,"Listen once to the service message."); const gtAudio = await audio(gtListen,"seed-audio-gt","Your bicycle repair appointment is Friday at eleven. Please bring the blue collection receipt."); await question(gt,gtListen,1,{type:QuestionTypeCode.SINGLE_CHOICE,prompt:"When is the appointment?",answers:["B"],strategy:MatchStrategy.EXACT,audioAssetId:gtAudio.id,options:[["A","Thursday at eleven"],["B","Friday at eleven"],["C","Friday at twelve"]]});
  const gtWrite = await section(gt,"Writing · Local Services",3,3600,Skill.WRITING,"Write a formal letter of at least 150 words."); await question(gt,gtWrite,1,{type:QuestionTypeCode.ESSAY,prompt:"Write to your local council about a service that should be improved.",answers:[],strategy:MatchStrategy.AI,points:9,metadata:{minimumWords:150}}); const gtSpeak = await section(gt,"Speaking · Daily Life",4,900,Skill.SPEAKING,"Prepare and record your response."); await question(gt,gtSpeak,1,{type:QuestionTypeCode.SPEAKING_TASK,prompt:"Describe a useful skill you learned from another person.",answers:[],strategy:MatchStrategy.AI,points:9,metadata:{prepSeconds:60,responseSeconds:120}}); await form(gt,"ielts-general-complete-1","General Training Complete Practice 1",[{sectionId:gtRead.id,order:1},{sectionId:gtListen.id,order:2},{sectionId:gtWrite.id,order:3},{sectionId:gtSpeak.id,order:4}]);

  const tfRead = await section(toefl,"Reading · Current Format",1,1800,Skill.READING,"Complete words, read daily-life material, and analyze an academic passage."); const tfPass = await passage(tfRead,"seed-passage-toefl","Coastal Forest Recovery","After severe storms, coastal forests often appear inactive. Underground root networks, however, may remain viable. Their stored energy supports new shoots before seedlings can establish, accelerating the first stage of recovery."); await question(toefl,tfRead,1,{type:QuestionTypeCode.GAP_FILL,prompt:"Complete the word: Root networks may remain v____ after a storm.",answers:["viable"],strategy:MatchStrategy.CASE_INSENSITIVE,passageId:tfPass.id}); await question(toefl,tfRead,2,{type:QuestionTypeCode.SINGLE_CHOICE,prompt:"What supports the first stage of recovery?",answers:["C"],strategy:MatchStrategy.EXACT,passageId:tfPass.id,options:[["A","Salt water"],["B","New roads"],["C","Stored energy in roots"],["D","Migrating animals"]]}); await question(toefl,tfRead,3,{type:QuestionTypeCode.MULTI_SELECT,prompt:"Select the TWO ideas stated in the passage.",answers:["A","D"],strategy:MatchStrategy.MULTI_PARTIAL,passageId:tfPass.id,options:[["A","Forests may look inactive"],["B","Roots always die"],["C","Seedlings arrive first"],["D","Root networks can remain viable"]]});
  const tfListen = await section(toefl,"Listening · Current Format",2,1740,Skill.LISTENING,"Listen and choose responses across conversation, announcement, and academic-talk contexts."); const tfAudio = await audio(tfListen,"seed-audio-toefl","The curator explains that the map was revised in eighteen forty two after a second survey revealed a previously unrecorded inlet."); await question(toefl,tfListen,1,{type:QuestionTypeCode.GAP_FILL,prompt:"The map was revised in ____.",answers:["1842"],strategy:MatchStrategy.EXACT,audioAssetId:tfAudio.id}); await question(toefl,tfListen,2,{type:QuestionTypeCode.SINGLE_CHOICE,prompt:"Why was the map revised?",answers:["B"],strategy:MatchStrategy.EXACT,audioAssetId:tfAudio.id,options:[["A","A gallery opened"],["B","A survey found an inlet"],["C","The paper was damaged"]]});
  const tfWrite = await section(toefl,"Writing · Current Format",3,1380,Skill.WRITING,"Build sentences, write an email, and contribute to an academic discussion."); await question(toefl,tfWrite,1,{type:QuestionTypeCode.ESSAY,prompt:"Write a concise email to a course coordinator requesting a change to a project meeting and explaining why.",answers:[],strategy:MatchStrategy.AI,points:6,metadata:{minimumWords:80}}); await question(toefl,tfWrite,2,{type:QuestionTypeCode.ESSAY,prompt:"Should universities require every student to complete a community project? Contribute to the academic discussion.",answers:[],strategy:MatchStrategy.AI,points:6,metadata:{minimumWords:100}}); const tfSpeak = await section(toefl,"Speaking · Current Format",4,480,Skill.SPEAKING,"Complete listen-and-repeat and interview-style responses."); await question(toefl,tfSpeak,1,{type:QuestionTypeCode.SPEAKING_TASK,prompt:"Listen-and-repeat practice: Clearly say, ‘The orientation begins beside the main library.’",answers:[],strategy:MatchStrategy.AI,points:6,metadata:{prepSeconds:5,responseSeconds:20}}); await question(toefl,tfSpeak,2,{type:QuestionTypeCode.SPEAKING_TASK,prompt:"Interview practice: Do you prefer studying alone or with a group? Give reasons.",answers:[],strategy:MatchStrategy.AI,points:6,metadata:{prepSeconds:15,responseSeconds:45}}); await form(toefl,"toefl-current-2026-1","TOEFL Current-format Practice 1",[{sectionId:tfRead.id,order:1},{sectionId:tfListen.id,order:2},{sectionId:tfWrite.id,order:3},{sectionId:tfSpeak.id,order:4}]);

  const greWrite = await section(gre,"Analytical Writing · Analyze an Issue",1,1800,Skill.WRITING,"Develop and support a clear position in 30 minutes."); await question(gre,greWrite,1,{type:QuestionTypeCode.ESSAY,prompt:"A society should measure progress primarily by the quality of its public institutions. Discuss the extent to which you agree.",answers:[],strategy:MatchStrategy.AI,points:6,metadata:{minimumWords:300}});
  const greVerbal = await section(gre,"Verbal · Stage 1",2,1080,Skill.VERBAL,"Complete the 18-minute first verbal stage."); await question(gre,greVerbal,1,{type:QuestionTypeCode.SINGLE_CHOICE,prompt:"Although the proposal appeared radical, its assumptions were surprisingly ____.",answers:["B"],strategy:MatchStrategy.EXACT,options:[["A","volatile"],["B","conventional"],["C","opaque"],["D","hostile"]]}); await question(gre,greVerbal,2,{type:QuestionTypeCode.MULTI_SELECT,prompt:"Select TWO words closest in meaning to prudent.",answers:["A","C"],strategy:MatchStrategy.MULTI_EXACT,options:[["A","careful"],["B","reckless"],["C","judicious"],["D","hasty"]]});
  const greVerbalEasy = await section(gre,"Verbal · Stage 2 Foundation",3,1380,Skill.VERBAL,"Foundation route selected from Stage 1 performance.",1); await question(gre,greVerbalEasy,1,{type:QuestionTypeCode.SINGLE_CHOICE,prompt:"The committee's brief statement was notably ____.",answers:["A"],strategy:MatchStrategy.EXACT,options:[["A","concise"],["B","turbulent"],["C","ornamental"],["D","remote"]]}); const greVerbalHard = await section(gre,"Verbal · Stage 2 Advanced",3,1380,Skill.VERBAL,"Advanced route selected from Stage 1 performance.",2); await question(gre,greVerbalHard,1,{type:QuestionTypeCode.SINGLE_CHOICE,prompt:"The critic was neither hostile nor uncritical; her assessment was carefully ____.",answers:["C"],strategy:MatchStrategy.EXACT,options:[["A","dismissive"],["B","obscure"],["C","qualified"],["D","capricious"]]});
  const greQuant = await section(gre,"Quantitative · Stage 1",4,1260,Skill.QUANT,"Complete the 21-minute first quantitative stage; use the calculator where permitted."); await question(gre,greQuant,1,{type:QuestionTypeCode.NUMERIC_ENTRY,prompt:"If 3x + 2 = 20, what is x?",answers:[6],strategy:MatchStrategy.NUMERIC_TOLERANCE,tolerance:0}); await question(gre,greQuant,2,{type:QuestionTypeCode.QUANT_COMPARISON,prompt:"Quantity A: 3². Quantity B: 2³.",answers:["A"],strategy:MatchStrategy.EXACT,options:[["A","Quantity A is greater"],["B","Quantity B is greater"],["C","The quantities are equal"],["D","Cannot be determined"]]});
  const greEasy = await section(gre,"Quantitative · Stage 2 Foundation",5,1560,Skill.QUANT,"Foundation route selected from Stage 1 performance.",1); await question(gre,greEasy,1,{type:QuestionTypeCode.NUMERIC_ENTRY,prompt:"What is 25% of 80?",answers:[20],strategy:MatchStrategy.NUMERIC_TOLERANCE,tolerance:0}); const greHard = await section(gre,"Quantitative · Stage 2 Advanced",5,1560,Skill.QUANT,"Advanced route selected from Stage 1 performance.",2); await question(gre,greHard,1,{type:QuestionTypeCode.NUMERIC_ENTRY,prompt:"If x² − 5x + 6 = 0, enter the larger root.",answers:[3],strategy:MatchStrategy.NUMERIC_TOLERANCE,tolerance:0});
  await form(gre,"gre-current-1","GRE Current-format Practice 1",[{sectionId:greWrite.id,order:1},{sectionId:greVerbal.id,order:2},{sectionId:greVerbalEasy.id,order:3,routeMaxPercent:69.999},{sectionId:greVerbalHard.id,order:3,routeMinPercent:70},{sectionId:greQuant.id,order:4},{sectionId:greEasy.id,order:5,routeMaxPercent:69.999},{sectionId:greHard.id,order:5,routeMinPercent:70}]);
  await prisma.testForm.updateMany({ where: { slug: { in: ["toefl-complete-1", "gre-complete-1"] } }, data: { isPublished: false } });
}

main().then(() => console.log("Seed complete: four published exam paths; demo password Practice123!")).finally(() => prisma.$disconnect());
